const videoData2 = [
  {
    id: '1',
    type: 'video',
    src: '/img/Download2.mp4',
    title: '나두 챌린지 참여',
    user: '사용자 1',
    userProfile: '/img/test.jpg',
    views: '10k',
    likes: '8.2k',
    comments: '1.2k',
    shares: '200',
    description: '오운완 챌린지 영상입니다. 함께 운동해요! #오운완',
  },
  {
    id: '2',
    type: 'image',
    src: '/img/img1.png',
    title: '산책 중',
    user: '사용자 2',
    userProfile: '/img/test.jpg',
    views: '5k',
    likes: '4.1k',
    comments: '1.0k',
    shares: '100',
    description: '오늘 산책 다녀왔어요!',
  },
  {
    id: '3',
    type: 'video',
    src: '/img/Download3.mp4',
    title: '운동 영상',
    user: '사용자 3',
    userProfile: '/img/test.jpg',
    views: '12k',
    likes: '10.5k',
    comments: '2.1k',
    shares: '250',
    description: '헬스장에서 운동하는 모습입니다.',
  },
  {
    id: '4',
    type: 'image',
    src: '/img/img2.png',
    title: '독서 타임',
    user: '사용자 4',
    userProfile: '/img/test.jpg',
    views: '7k',
    likes: '6.2k',
    comments: '1.5k',
    shares: '150',
    description: '오늘의 독서 시간입니다.',
  },
  {
    id: '5',
    type: 'video',
    src: '/img/Download.mp4',
    title: '요리 영상',
    user: '사용자 5',
    userProfile: '/img/test.jpg',
    views: '15k',
    likes: '12.8k',
    comments: '3.2k',
    shares: '300',
    description: '요리하는 모습을 담은 영상입니다.',
  },
  {
    id: '6',
    type: 'image',
    src: '/img/Download3.png',
    title: '커피 한잔',
    user: '사용자 6',
    userProfile: '/img/test.jpg',
    views: '6k',
    likes: '5.0k',
    comments: '1.2k',
    shares: '120',
    description: '아침 커피 한잔의 여유.',
  },
  {
    id: '7',
    type: 'video',
    src: '/img/Download4.mp4',
    title: '운동 루틴',
    user: '사용자 7',
    userProfile: '/img/test.jpg',
    views: '11k',
    likes: '9.4k',
    comments: '2.0k',
    shares: '220',
    description: '매일 운동하는 루틴을 소개합니다.',
  },
  {
    id: '8',
    type: 'image',
    src: '/img/Download4.png',
    title: '여행 사진',
    user: '사용자 8',
    userProfile: '/img/test.jpg',
    views: '8k',
    likes: '7.1k',
    comments: '1.7k',
    shares: '180',
    description: '여행 중 찍은 사진입니다.',
  },
  {
    id: '9',
    type: 'video',
    src: '/img/Download1.mp4',
    title: '운동 동기부여',
    user: '사용자 9',
    userProfile: '/img/test.jpg',
    views: '13k',
    likes: '11.6k',
    comments: '2.5k',
    shares: '270',
    description: '운동 동기부여 영상입니다.',
  },
  {
    id: '10',
    type: 'image',
    src: '/img/Download1.png',
    title: '아름다운 풍경',
    user: '사용자 10',
    userProfile: '/img/test.jpg',
    views: '9k',
    likes: '8.0k',
    comments: '1.9k',
    shares: '200',
    description: '아름다운 풍경 사진입니다.',
  },
];

const getVideoData2 = async (index) => {
  return videoData2[index] || null;
};

export default getVideoData2;
